sudo apt-get install python-ldaptor
# fix bug in ldaptor
for f in $(find /usr/lib/python2.7/dist-packages/ldaptor -name "*.py")
do
	sudo sed -i 's/log\.debug/log.msg/' $f
done
sudo pip install python-pam


####
Gerrit tries to insert a row into the account_external_ids table with external_id='gerrit:<uid>'
Gerrit will attempt to create a new account number if gerrit:<uid> row doesn't already exist.
Have to remove the existing entry with external_id='username:<uid>'
For cleanup, should also remove corresponding entry with external_id='<google-id-url>'
